"""Audit required property fields and exact duplicate identifiers."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "src" / "data" / "properties-import.json"
REPORT_FILE = ROOT / "property-quality-report.md"
PLACEHOLDER = "/images/placeholders/property-placeholder.webp"


def _missing(records: list[dict], getter) -> list[str]:
    return [str(record.get("id", "unknown")) for record in records if not getter(record)]


def _duplicates(records: list[dict], field: str) -> list[str]:
    values = [str(record.get(field, "")).strip() for record in records]
    counts = Counter(value for value in values if value)
    return sorted(value for value, count in counts.items() if count > 1)


def main() -> int:
    records = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    checks = {
        "Missing price": _missing(records, lambda item: isinstance(item.get("price"), (int, float)) and item["price"] > 0),
        "Missing size": _missing(records, lambda item: str(item.get("size", "")).strip() and str(item.get("unit", "")).strip()),
        "Missing sector": _missing(records, lambda item: str((item.get("location") or {}).get("sector", "")).strip()),
        "Missing type": _missing(records, lambda item: str(item.get("propertyType", "")).strip()),
        "Missing image": _missing(records, lambda item: bool((item.get("images") or [{}])[0].get("url"))),
    }
    duplicate_ids = _duplicates(records, "id")
    duplicate_slugs = _duplicates(records, "slug")
    duplicate_sources = _duplicates(records, "sourceUrl")
    placeholder_count = sum((item.get("images") or [{}])[0].get("url") == PLACEHOLDER for item in records)
    issue_count = sum(len(items) for items in checks.values()) + len(duplicate_ids) + len(duplicate_slugs) + len(duplicate_sources)

    lines = [
        "# Property Quality Report",
        "",
        "Generated by `scripts/property_quality_audit.py`.",
        "",
        "## Summary",
        "",
        f"- Total properties: {len(records)}",
        f"- Complete records: {len(records) - len(set().union(*checks.values()))}",
        f"- Placeholder images: {placeholder_count}",
        f"- Quality issues: {issue_count}",
        "",
        "## Required Fields",
        "",
        *(f"- {name}: {len(items)}" for name, items in checks.items()),
        "",
        "## Duplicate Properties",
        "",
        f"- Duplicate IDs: {len(duplicate_ids)}",
        f"- Duplicate slugs: {len(duplicate_slugs)}",
        f"- Duplicate source URLs: {len(duplicate_sources)}",
        "",
        "Exact IDs, slugs, and source URLs are treated as duplicate-property signals. Similar market attributes alone are not sufficient because multiple listings may legitimately share sector, size, type, and price.",
        "",
        "## Details",
        "",
    ]
    details = {**checks, "Duplicate IDs": duplicate_ids, "Duplicate slugs": duplicate_slugs, "Duplicate source URLs": duplicate_sources}
    for name, items in details.items():
        lines.extend([f"### {name}", "", ", ".join(items) if items else "None.", ""])
    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Audited {len(records)} properties: {issue_count} issues. Report: {REPORT_FILE}")
    return 1 if issue_count else 0


if __name__ == "__main__":
    raise SystemExit(main())
